interface Resources {
  "translation": {
    "LanguageSwitch": {
      "en": "English",
      "vi": "Vietnamese"
    },
    "SelectLanguage": {
      "language": "Select Language"
    },
    "NotFoundPage": {
      "title": "404 NOT FOUND",
      "message": "The page you are looking for does not exist, sorry for the inconvenience.",
      "homeButton": "Home",
      "loginButton": "Login"
    },
    "Auth": {
      "hi": "Hello",
      "beforeLogin": "Sign in to manage your job listings now!",
      "userTitle": "Username",
      "passwordTitle": "Password",
      "fgPassword": "Forgot password",
      "loginBtn": "Login",
      "plsUser": "Please enter username",
      "plsPass": "Please enter password",
      "loginWarning": "Please check your account or password again",
      "notAccount": "Do not have an account ?",
      "loginBy": "Sign in with",
      "or": "Or",
      "signupTitle": "Sign Up",
      "signupSubtitle": "Sign up to manage your task list now!",
      "usernameLabel": "Username",
      "fullNameLabel": "Full Name",
      "emailLabel": "Email",
      "phoneLabel": "Phone Number",
      "passwordLabel": "Password",
      "branchLabel": "Branch",
      "sexLabel": "Gender",
      "imageLabel": "Profile Picture",
      "submitButton": "Sign Up",
      "loginPrompt": "Already have an account?",
      "loginLink": "Log in",
      "usernamePlaceholder": "Username",
      "fullNamePlaceholder": "Full Name",
      "emailPlaceholder": "Email",
      "phonePlaceholder": "Phone Number",
      "passwordPlaceholder": "Password",
      "branchPlaceholder": "Please select a branch",
      "sexPlaceholder": "Please select a gender",
      "imagePlaceholder": "Choose a profile picture",
      "usernameError": "Please enter a username",
      "fullNameError": "Please enter your full name",
      "emailError": "Please enter an email",
      "phoneError": "Please enter a phone number",
      "passwordError": "Please enter a password",
      "branchError": "Please select a branch",
      "sexError": "Please select a gender",
      "imageError": "Please provide a profile picture",
      "requestPasswordReset": "Request Password Reset",
      "enterYourEmail": "Please enter your email to reset your password.",
      "email": "Email",
      "enterEmail": "Enter your email",
      "emailRequired": "Email is required",
      "requestReset": "Request Password Reset",
      "resetLinkSent": "Password reset request sent successfully!",
      "resetLinkFailed": "Failed to send password reset request"
    },
    "LandingPage": {
      "Collapse": "Collapse",
      "Contact": "Contact",
      "ContactConsulting": "Contact Consulting",
      "Navbar": {
        "Home": "Home",
        "BookingInfo": "Booking Information",
        "FindTicket": "Find Ticket",
        "ReturnTicket": "Return Ticket",
        "CheckTicket": "Check Ticket",
        "TrainTimePrice": "Train Time & Price",
        "Promotion": "Promotion",
        "Regulations": "Regulations",
        "Guidance": "Guidance",
        "Contact": "Contact",
        "Hotline": "Hotline: 0333133050",
        "Email": "Email: fpttrain@gmail.com",
        "Theme": "Theme",
        "Translate": "Translate"
      },
      "BannerTitle": "Book Train Tickets Online",
      "BannerSubtitle": "The Best Choice for Your Journey",
      "SearchButton": "Search",
      "DeparturePlaceholder": "Departure...",
      "DestinationPlaceholder": "Destination...",
      "DepartureDatePlaceholder": "Departure Date",
      "ReturnDatePlaceholder": "Return Date",
      "AgeSelectDefault": "Select Age Group",
      "SectionOneTitle": "Compare Cheap Train And Bus Tickets With Flights",
      "SectionOneDescription": "With FPT Train, you can compare flight tickets with train and bus tickets.",
      "SectionTwoTitle": "Easily Find Cheap Tickets",
      "SectionTwoDescription": "Search and book cheap flights, buses, ferries, and trains! Find the best deals with FPT Train.",
      "SectionThreeTitle": "Schedules And Tickets For All Your Travel Needs",
      "SectionThreeDescription": "Booking train, bus, flight, or ferry tickets has never been easier."
    }
  }
}

export default Resources;
